// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qodigqcvbdhknekukmac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZGlncWN2YmRoa25la3VrbWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDc0MzUsImV4cCI6MjA2ODYyMzQzNX0.8t4mVtZ6moKNjk0gC_M6OQ3HoPYBHBV24CiNiwooRSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);